### ISSUE TITLE
java.lang.RuntimeException: Value for parquet.scalapb.class not found.

### ISSUE THREAD

**Issue by caitlinhickey** [scalapb/sparksql-scalapb#12]
When using the method ProtoParquet.loadParquet[T](), ScalaPBReadSupport in prepareForRead searches the parquet file metadata for a key called "parquet.scalapb.class". If the footer of the  parquet file that it is reading doesn't contain that key, and a class value, prepareForRead throws the above error. This seems like unintended behavior because loadParquet is passed the proto class explicitly. This also prevents scalapb from reading any parquet files that weren't created by scalapb.

**Comment by thesamet** [comment]
Thanks for reporting. It looks like you started debugging this issue - will you be able to work on a PR?

**Comment by caitlinhickey** [comment]
Hi, my apologies for taking so long to respond. I'm planning to start working on this next week. Thanks!

**Comment by caitlinhickey** [comment]
Hi, I've done a little bit of work on this, but it doesn't seem to have a simple fix. The problem is that you need a string of the class type name (invariant) for line 19, in ScalaPBReadSupport, but scala's type erasure makes this incredibly difficult to acquire. At this time, because this is not a blocker for me, I'm going to withdraw my attempts to fix. I'd be more than willing to answer questions about the issue, and I'll check back in the future, in hopes that it gets changed.

**Comment by thesamet** [comment]
Thanks again for looking into this @caitlinhickey - if you could can you provide a minimal example that gets this exception thrown.
