### ISSUE TITLE
Schema generation invalid for JSON Protos with Int64 values represented as Strings

### ISSUE THREAD

**Issue by amay15** [scalapb/sparksql-scalapb#17]
I'm attempting to parse json protos in a spark structured stream from kinesis using the from_json method on the json string while using the ProtoSQL.schemaFor function to create the message schema.

The proto definition has int64 fields that according to the proto json spec are represented as strings. However the schema generator is assuming they're represented as long values. When Spark parses the json it fails when it finds string values instead of long values and the entire column is nulled out (including valid nested values).

The scalapb library for json protos handles this case, but the schema generation for Spark SQL doesn't.

Is there a better way to do this?

**Comment by thesamet** [comment]
Interesting. I think we'd have to have our own Spark json reader (or customize Spark's json reader) that understands the schema so it can do the right conversions.

**Comment by thesamet** [comment]
For future reference, the solution would probably be to read the json into spark. Then convert the string column to long column using Spark functions and then pass to ScalaPB.
