### ISSUE TITLE
object TimestampProtoUdt is not a member of package com.google.protobuf.timestamp

### ISSUE THREAD

**Issue by shahbaaz-ahmed** [scalapb/sparksql-scalapb#27]
Hi , has anyone used ScalaPB with a .proto file containing a timestamp type ?

I seem to get this error when doing sbt compile
`object TimestampProtoUdt is not a member of package com.google.protobuf.timestamp`

my `scalapb.sbt` looks like;
```addSbtPlugin("com.thesamet" % "sbt-protoc" % "0.99.25")
libraryDependencies += "com.thesamet.scalapb" %% "compilerplugin" % "0.9.4"
libraryDependencies += "com.thesamet.scalapb" %% "sparksql-scalapb-gen" % "0.8.2"
```

my proto file looks like ;

```syntax = "proto3";
package proto;

import "google/protobuf/timestamp.proto";

message Event{
    int64 applicationId = 1; 
    ApplicationState state = 2;
    ApplicationState previousState = 3;
    google.protobuf.Timestamp timeStamp = 4; 

    enum ApplicationState {
       None = 0;
       Approved = 1;
       Declined = 2;
       Duplicate = 3;
       AwaitingApproval = 4;
       Dead = 5;
    }
}
```

i have the following in my build sbt;

```PB.targets in Compile := Seq(
  scalapb.gen() -> (sourceManaged in Compile).value,
  scalapb.UdtGenerator -> (sourceManaged in Compile).value
)
```
and this in `plugins.sbt`
`libraryDependencies += "com.thesamet.scalapb" %% "sparksql-scalapb-gen" % "0.8.2"`

any help would be appreciated

**Comment by thesamet** [comment]
It looks like you need to call the UdtGenerator for the messages provided by timestamp.proto.

You can do this in a separate sub-project in a multiproject SBT build. See this [example SBT file](https://github.com/thesamet/sbt-protoc/blob/b6a2587c14b2af3941bec467d182146d2f240b27/examples/multi-with-external-jar/build.sbt#L16). The highlighted line adds to the list of sources files that are coming from external JAR (update it so it captures the protos you want). The reason we shouldn't add this line to your main project is that you want to avoid invoking `scalapb.gen()` on those file as ScalaPB runtimes already includes Scala generated code for those protos.

**Comment by thesamet** [comment]
Next step: add google's protobuf UDTs into sparksql-scalapb

**Comment by thesamet** [comment]
UDTs are no longer necessary in latest version of sparksql-scalapb. Closing.
