### ISSUE TITLE
Bugs when read from compatible proto definition

### ISSUE THREAD

**Issue by ukby1234** [scalapb/sparksql-scalapb#313]
proto definitions: 
```
syntax = "proto3";

package scalapb.spark.schema.bug;

message Write {
  repeated RepeatedNestedWrite nested_field = 6;
  string additional_field = 14;
}

message RepeatedNestedWrite {
  RepeatedOmitWrite omit_for_read = 2;
  string field_one = 7;
  string field_two = 8;
  Nested persisted = 9;
}

message RepeatedOmitWrite {
  string field_one = 5;
  string field_two = 6;
}

message Nested {
  string field_one = 5;
}

message Read {
  repeated RepeatedNestedRead nested_field = 6;
  string additional_field = 14;
}

message RepeatedNestedRead {
  string field_one = 7;
  string field_two = 8;
  Nested persisted = 9;
}
```
Steps to reproduce: 1) write some data with the `Write` class 2) read the data with `Read`, and it results in Spark exceptions. `java.lang.NegativeArraySizeException`. 
a PR to fix this is on the way.

**Comment by ukby1234** [comment]
PR opened: https://github.com/scalapb/sparksql-scalapb/pull/314

**Comment by ukby1234** [comment]
@thesamet Can you do a release? Our projects need this bugfix; otherwise, we need to fork this repo and build a custom version.

**Comment by thesamet** [comment]
Sure, I've just kicked off a release (v1.0.3). It should be available on maven shortly. https://github.com/scalapb/sparksql-scalapb/actions/runs/4663535643/jobs/8254944857

**Comment by ukby1234** [comment]
@thesamet Thank you so much!
