### ISSUE TITLE
Migrating to version 1.0.2 from version pre 0.10.5

### ISSUE THREAD

**Issue by intigonzalez** [scalapb/sparksql-scalapb#332]
**Problem**
A breaking change was introduced in version 0.10.5.

See: https://github.com/scalapb/sparksql-scalapb/blob/master/CHANEGELOG.md#breaking-changes

> Protobuf maps are now represented as Spark in maps. Prior to this change maps were represented as a list of key-value structs. (#79)

Today we have data in production using the _old_ schema encoding and when we try to migrate to version 1.0.2 we see a different schema.

**Example**
Old schema (data read using Spark  Dataframe without using SparkSql-ScalaPb). So this is what we have stored.

```
-- filters: array (nullable = true)
    -- element: struct (containsNull = true)
        -- key: string (nullable = true)
        -- value: string (nullable = true)
```

When we migrate to version 1.0.2 the generated schema is:

```
 -- filters: map (nullable = true)
      -- key: string
      -- value: string (valueContainsNull = true)
```

Spark is unable to use the new schema to read the previous data.

I was wondering a few things:

1.  Is there an official migration mechanism ? Was this considered when the default representation for Map was changed ?
2.  Is there a way to keep using the _old_ schema ? Array of tuples ?

For this second part I tried:
1. Using `withMessageEncoder`, but the type I am trying to handle doesn't have a `Descriptor`. Its type is just `Map[String, String]`
2. Overriding the implementation of `ProtoSql`. But somehow the new schema is still used.

(see below my own implementation of ProtoSql)
```
class MyProtoSql(val s: SchemaOptions) extends ProtoSQL(s) { self2 =>
  override def dataTypeFor(fd: FieldDescriptor): DataType =
    if (fd.isMapField) fd.scalaType match {
      case ScalaType.Message(mapEntry) =>
        ArrayType(
          StructType(
            Seq(
              StructField("key", singularDataType(mapEntry.findFieldByNumber(1).get)),
              StructField("value", singularDataType(mapEntry.findFieldByNumber(2).get))
            )
          )
        )
      case _ => super.dataTypeFor(fd)
    }
    else super.dataTypeFor(fd)

  override val implicits: Implicits = new Implicits {
    val typedEncoders: TypedEncoders = new TypedEncoders {
      val protoSql: MyProtoSql = self2
    }
  }
}
```

Question again is there a smooth migration path ?

**Comment by thesamet** [comment]
Hi @intigonzalez , we don't have a migration path right now. It's certainly a miss to introduce this breaking change without providing a flag to allow the old behavior so users can load the data in one format and save in the other. How much data you have and how complex is it? If you only have a few maps, then you could write a spark transformation to modify the schema of your existing data to the new format.

**Comment by thesamet** [comment]
One thing you can do is this:
1. Using the old sparksql-scalapb version, load the data, and serialize it in protobuf binary format (`_.map(_.toByteArray)`).
2. Using the new version, load the binary data `data.map(MyMessage.parseFrom(_))`.
3. Write again the new data back to storage in the format you used before.

**Comment by intigonzalez** [comment]
> If you only have a few maps, then you could write a spark transformation to modify the schema of your existing data to the new > format.

I think this would do. I have several TB of data but luckily only a few maps (and a few downstream readers + we know all of them). In principle this should be doable.
I would need to do some magic to do it in prod without stopping the pipeline, but it should be Ok.

Thanks a lot
