### ISSUE TITLE
Support for spark 3.4 and 3.5

### ISSUE THREAD

**Issue by shubhamvij** [scalapb/sparksql-scalapb#366]
**Problem**

Only up to spark 3.3 is supported. It would be helpful to release some targets for newer versions (3.4, 3.5) of spark.

**Comment by shubhamvij** [comment]
Opened pull request: https://github.com/scalapb/sparksql-scalapb/pull/365

**Comment by shubhamvij** [comment]
@thesamet Thanks for the quick review/merge.
Do you mind kicking of a release as well?

**Comment by thesamet** [comment]
Released v1.0.4.

**Comment by thesamet** [comment]
Thanks for putting together the PR!
