### ISSUE TITLE
map<string, string> field not Serializable

### ISSUE THREAD

**Issue by ManasGeorge** [scalapb/sparksql-scalapb#41]
Having a map<string, string> field in the Protobuf schema makes the SimplePerson spec become unserializable because adding maps brings in an instance of the unserializable TypeMapper class into the generated classes. Are map types not supported?

**Comment by thesamet** [comment]
Thanks for reporting. I'd like maps to be supported, and it's not something currently covered under tests. I'll take a look soon.

**Comment by thesamet** [comment]
This is resolved if you upgrade ScalaPB to 0.9.6. I am also working on enhancing sparksql-scalapb so it uses spark maps rather than creating arrays of key-value structs.

**Comment by ManasGeorge** [comment]
Thank you so much, can confirm that it works smoothly now! 😄
