### ISSUE TITLE
Friendlier SQL encoding for google wrappers

### ISSUE THREAD

**Issue by mattforbes-gr** [scalapb/sparksql-scalapb#71]
We've forked this library to add some automatic conversion for google's wrapper types/timestamps such that they get encoded as more SQL-friendly types. For example google.protobuf.Int32Value is represented as an IntegerType rather than a StructType with a nested value (enabling `SELECT my_int_field` instead of `SELECT my_int_field.value`). This is a workaround so that we can preserve NULLability but not require the manual unwrapping at query time. Additionally we encode google.protobuf.Timestamp as a TimestampType so that the SQL date functions work natively without converting in the query.

@thesamet is this something you'd welcome as a PR (gated behind an option)?

**Comment by thesamet** [comment]
Sounds great. would be interested in seeing a PR. Thank you!

**Comment by thesamet** [comment]
I added a change that supports better encoding for primitive wrappers. It is now optional, but will become the default on 0.11.x.

**Comment by mattforbes-gr** [comment]
@thesamet awesome! Sorry that I never found the time to port over our solution.
